### ISSUE TITLE
`TypeError: Cannot read property 'then' of undefined` 

### ISSUE THREAD

**Issue by p0358** [makigas/discordjs-reaction-role#26]
I keep getting this, and it seems to be caused by the code assuming that extractRole will always return a role, but not all reactions users make are related to role pickup, so this keeps spamming the console. The promise should probably return `Role?`, and the return value of the functions should be stored into a variable and checked before executing .then on it. For optimization it could be moved before the member fetch, to return without any API requests in case the reaction is not configured for any roles in the config at all

**Comment by danirod** [comment]
Totally looks like a bug. Turning on strict mode on tsc catches this. My bad for overlooking this.

**Comment by danirod** [comment]
I've updated 1.0.1 patching this bug. Let's hope it makes the error messages dissapear from the logs.

Thank you for your report, I certainly have errors in the log of my own Discord bot but I never figured out that it was related to this function.
