### ISSUE TITLE
TypeError: ReactionRole is not a constructor WITH ES MODULES

### ISSUE THREAD

**Issue by ALWISHARIFF** [makigas/discordjs-reaction-role#98]
MY NODE VERSION:node v16.14.2,
OS:WINDOWS:10,
discordjs-reaction-role: "^2.1.1",
discord.js: "^13.6.0",

```js 
import { Client, Intents } from "discord.js";
import ReactionRole from 'discordjs-reaction-role';

import config from './config/config.json' assert { type: 'json' };;

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES, Intents.FLAGS.GUILD_MEMBERS, Intents.FLAGS.DIRECT_MESSAGES, Intents.FLAGS.GUILD_MESSAGE_REACTIONS] });

new ReactionRole(client, [{ messageId: "965629960666644520", reaction: "🔔", roleId: "965590388788301944" }])
const token = config.token;

client.on("ready", () => {
    // client.channels.cache.get("965574795817254912").send('Hello here!');

    console.log("Ready BOT!");
})

client.login(token)
```
I cant call the constructor i tried ```console.log(ReactionRole) ```after import i found out that the class is in an object with a key called default ```{default:CLASS}``` so i call ```new ReactionRole.default(client, [{ messageId: "965629960666644520", reaction: "🔔", roleId: "965590388788301944" }])``` The reactions are not registered!Doesnt detect any reactions and roles not assigned!

**Comment by ALWISHARIFF** [comment]
Please check the discussion i solved the issue Alhamdulillah by putting the intents and partials the code is available in the discussions
Thank you

**Comment by danirod** [comment]
I'll do my best, unfortunately I do not understand why GitHub does not send me notifications on discussions. Thank you for the patience!
